 SELECT
  PO.PRODUCT_MODEL_ID,
  LD.REASON2,
  SUM(LD.DEFECT_QTY) AS DEFECT_QTY
FROM
  PRODUCT_ORDERS PO,
  WORK_ORDERS WO,
  (
		SELECT
    WORK_ORDER_ID,
    REASON2,
    CREATED_AT,
    SUM (1) AS DEFECT_QTY
  FROM
    LOT_DEFECTS
  GROUP BY
			WORK_ORDER_ID,
			CREATED_AT,
			REASON2
	) LD
WHERE WO.PRODUCT_ORDER_ID = PO. ID
  AND WO.ID = LD.WORK_ORDER_ID
  AND LD.CREATED_AT >= "TRUNC" (SYSDATE, 'MM')
  AND LD.CREATED_AT <= LAST_DAY (SYSDATE)
GROUP BY
	PO.PRODUCT_MODEL_ID,
	LD.REASON2
ORDER BY PO.PRODUCT_MODEL_ID