SELECT
	'02' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'04' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'06' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'08' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'12' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'14' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'16' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'18' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'20' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6
UNION ALL
SELECT
	'22' as date,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line1,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line2,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line3,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line4,
    ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line5,
	ROUND(CAST(RANDOM() * 300 AS NUMERIC), 0) AS line6

