SELECT
      A.WORK_DATE AS 日期,
      A.LINE AS 线别,
      A.DATA_1 AS 产品组,
      A.MAT_ID AS 产品编码,
      A.MAT_DESC AS 产品描述,
      A.ORDER_ID AS 工单,
      A.OPER,
      A.OPER_DESC AS 工序,
      A.SHIFT AS 班次,
      COUNT(DISTINCT A.LOT_ID) AS 数量
FROM (
      SELECT
            (CASE
            WHEN TO_NUMBER(substr(A.TRAN_TIME,9,6)) - TO_NUMBER(SUBSTR('20180627' || '08' || '30',9,6)) >= 0
            THEN TO_CHAR(TO_DATE(A.TRAN_TIME,'YYYYMMDDHH24MISS'),'YYYY-MM-DD')
            ELSE
            TO_CHAR(TO_DATE(A.TRAN_TIME,'YYYYMMDDHH24MISS') - 1,'YYYY-MM-DD')
            END) AS WORK_DATE,
            (SELECT DISTINCT DATA_1 FROM MGCMTBLDAT WHERE TABLE_NAME = 'SUB_AREA' AND FACTORY = A.FACTORY AND KEY_1 = A.LINE_ID) AS LINE,
            C.DATA_1,
            A.MAT_ID,
            B.MAT_DESC,
            A.ORDER_ID,
	    A.OLD_OPER OPER,
            D.OPER_DESC,
            (CASE WHEN A.SHIFT_ID = '1' THEN '白班' ELSE '晚班' END) SHIFT,
            A.LOT_ID
      FROM CWIPLOTMVH A
      LEFT OUTER JOIN MWIPOPRDEF D
      ON D.FACTORY = A.FACTORY
      AND D.OPER = A.OLD_OPER
      LEFT OUTER JOIN MWIPMATDEF B
      ON A.FACTORY = B.FACTORY
      AND A.MAT_ID = B.MAT_ID
      LEFT OUTER JOIN ( select DISTINCT FACTORY,KEY_1,DATA_1,DATA_2 from MGCMTBLDAT WHERE TABLE_NAME='PRODUCT_GRP' ) C
      ON C.FACTORY = B.FACTORY AND C.KEY_1 = B.MAT_CMF_1
      WHERE A.TRAN_TIME >= '20180627'||'08'||'30'||'00'
      AND A.TRAN_TIME < '20180628'||'08'||'30'||'00'
      AND A.FACTORY = NVL(trim(' '),A.FACTORY)
      AND A.SEQ_NUM = 1
      AND C.DATA_1 LIKE '%SDT%'
      AND A.ORDER_ID =  NVL (TRIM (' '), A.ORDER_ID)
      AND A.SHIFT_ID = NVL (TRIM (' '), A.SHIFT_ID)
            AND A.HIST_DEL_FLAG = ' '
      AND (CASE WHEN A.OLD_OPER = '120070' AND A.BOARD_SIDE IN ( 'S',' ') AND A.TRAN_CODE IN ('END', 'COLLECT_DFT')
                    THEN 1
                    WHEN A.OLD_OPER = '120070' AND A.BOARD_SIDE IN ( 'T','B') AND A.TRAN_CODE IN ('CREATE','END', 'COLLECT_DFT')
                    THEN 1
                    WHEN A.OLD_OPER <> '120070' AND A.TRAN_CODE IN ('END', 'COLLECT_DFT')  THEN 1
                    ELSE 2
              END )  = 1
      ) A
GROUP BY A.WORK_DATE, A.LINE, A.DATA_1, A.MAT_ID, A.MAT_DESC, A.ORDER_ID, A.OPER,A.OPER_DESC, A.SHIFT
ORDER BY A.WORK_DATE DESC
