SELECT /*+ index( MWIPLOTHIS_IDX_4 ) */
       A.ORDER_ID AS 工单,
       D.TASK_ORDER AS 任务令,
       A.MAT_ID AS 产品编码,
       A.LOT_ID AS SN,
       A.FLOW AS 工艺路线,
       B.OPER_DESC AS 工序,
       E.DATA_1  AS 工位,
       (CASE WHEN NVL(A.LOT_CMF_14,' ') <> ' ' THEN A.LOT_CMF_14
         ELSE A.LOT_CMF_13
           END ) AS 板边条码,
      A.LOT_CMF_15  AS 面别,
      A.LOT_CMF_12  AS 轨道,
      A.LOT_CMF_2 AS 状态,
      (CASE WHEN A.LOT_CMF_1 = '1' THEN '白班'
                ELSE '晚班'
                END) AS 班次,
       C.USER_DESC AS 作业人,
       A.TRAN_USER_ID AS 工号,
       TO_CHAR(TO_DATE((CASE WHEN A.TRAN_TIME = ' ' THEN '20990101000000'
          ELSE A.TRAN_TIME
          END ), 'yyyymmddhh24miss'),
               'yyyy-mm-dd hh24:mi:ss') AS 作业时间,
      (CASE
      WHEN A.TRAN_CMF_2 ='A' THEN '自动'
      ELSE '手动'
      END ) AS 作业方式
  FROM MWIPLOTHIS A
  LEFT JOIN MWIPOPRDEF B
    ON B.FACTORY = A.FACTORY AND B.OPER = A.OLD_OPER
  LEFT OUTER JOIN MWIPMATDEF E
    ON A.FACTORY = E.FACTORY
    AND A.MAT_ID = E.MAT_ID
  LEFT JOIN CWIPORDDEF D
    ON D.FACTORY = A.FACTORY AND D.ORDER_ID = A.ORDER_ID
  LEFT JOIN MSECUSRDEF C
    ON C.FACTORY = A.FACTORY AND C.USER_ID = A.TRAN_USER_ID
  LEFT JOIN MGCMTBLDAT E    ON  E.TABLE_NAME='WORK_STATION' AND A.LOT_CMF_18 =E.KEY_1 AND A.OLD_OPER=E.KEY_2
 WHERE A.HIST_DEL_FLAG = ' '
    AND A.FACTORY = NVL(TRIM('RCM1'),A.FACTORY)
    AND (CASE WHEN A.OLD_OPER = '120070' AND A.LOT_CMF_15 IN ( 'S',' ') AND A.TRAN_CODE IN ('END', 'COLLECT_DFT')
          THEN 1
            WHEN A.OLD_OPER = '120070' AND A.LOT_CMF_15 IN ( 'T','B') AND A.TRAN_CODE IN ('CREATE','END', 'COLLECT_DFT')
          THEN 1
            WHEN A.OLD_OPER <> '120070' AND A.TRAN_CODE IN ('END', 'COLLECT_DFT')  THEN 1
          ELSE  2
        END )  = 1
    AND A.ORDER_ID = NVL (TRIM ('FBFB18060DX'), A.ORDER_ID)
    AND D.TASK_ORDER = NVL (TRIM (' '), D.TASK_ORDER)
            AND E.MAT_CMF_1 = '20'
    AND A.LOT_ID = NVL (TRIM (' '), A.LOT_ID)
    AND A.LOT_CMF_15 = NVL (TRIM (' '), A.LOT_CMF_15)
    AND A.LOT_CMF_12 = NVL (TRIM (' '), A.LOT_CMF_12)
    AND A.TRAN_USER_ID = NVL (TRIM (' '), A.TRAN_USER_ID)
    AND A.TRAN_TIME >= '20180627'||'08'||'30'||'00'
    AND A.TRAN_TIME < '20180628'||'08'||'30'||'00'
    AND ROWNUM <=50000
ORDER BY A.ORDER_ID, D.TASK_ORDER,A.LOT_ID, A.HIST_SEQ, A.TRAN_TIME
