SELECT rownum rn9__, A.*  FROM ( SELECT LOT_ID AS LOT_ID , MAT_ID AS MAT_ID , FLOW AS FLOW , OPER_DESC AS OPER_DESC , QTY_1 AS QTY_1 , OWNER_CODE AS OWNER_CODE , END_TIME AS END_TIME , ORG_DUE_TIME AS ORG_DUE_TIME , OPER_IN_TIME AS OPER_IN_TIME , 班次 AS 班次 , 产品状态 AS 产品状态 , FQA抽检批 AS FQA抽检批 , 小箱号 AS 小箱号 , 板边条码1 AS 板边条码1 , 板边条码2 AS 板边条码2 , 工厂 AS 工厂 , 产线 AS 产线 , LINE_DESC AS LINE_DESC , 工位 AS 工位 , LAST_TRAN_CODE AS LAST_TRAN_CODE
FROM (SELECT A.LOT_ID,
A.MAT_ID,
A.FLOW,
(CASE
  WHEN A.OPER = ' ' THEN ' '
  ELSE (SELECT F.OPER_DESC FROM MWIPOPRDEF F WHERE F.OPER = A.OPER)
END) AS OPER_DESC,
A.QTY_1,
A.OWNER_CODE,
TO_CHAR(to_date(trim(END_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') END_TIME,
TO_CHAR(to_date(trim(ORG_DUE_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') ORG_DUE_TIME,
TO_CHAR(to_date(trim(OPER_IN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') OPER_IN_TIME,
(CASE
  WHEN A.LOT_CMF_1 = ' ' THEN ' '
  ELSE (SELECT G.DATA_1 FROM MGCMTBLDAT G WHERE G.TABLE_NAME = 'SHIFT' AND G.KEY_1 = A.LOT_CMF_1 AND A.FACTORY = G.FACTORY)
END) AS 班次,
A.LOT_CMF_2 AS 产品状态,
A.LOT_CMF_3 AS FQA抽检批,
A.LOT_CMF_4 AS 小箱号,
A.LOT_CMF_13 AS 板边条码1,
A.LOT_CMF_14 AS 板边条码2,
A.LOT_CMF_16 AS 工厂,
A.LOT_CMF_17 AS 产线,
(CASE
  WHEN A.LOT_CMF_17 = ' ' THEN ' '
  ELSE (SELECT G.DATA_1 FROM MGCMTBLDAT G WHERE G.TABLE_NAME = 'SUB_AREA' AND G.KEY_1 = A.LOT_CMF_17 AND A.FACTORY = G.FACTORY)
END) AS LINE_DESC,
A.LOT_CMF_18 AS 工位,
A.LAST_TRAN_CODE
FROM MWIPLOTSTS A
WHERE A.FACTORY =  'RCM1'
AND (case
         when trim( 'FBFB180609A' ) is null then
1
         when trim( 'FBFB180609A' ) = A.ORDER_ID then
1
         else
0
       end) = 1
AND (case
         when trim( ' ' ) is null then
1
         when trim( ' ' ) = A.OPER then
1
         else
0
       end) = 1
ORDER BY A.OPER) A
 ) A  WHERE ROWNUM < 10000
