SELECT
A.ORDER_ID  AS 工单,
A.MAT_ID AS 产品编码,
A.FLOW AS "工艺路线",
A.Lot_Id AS  SN,
A.LOT_CMF_2 AS 状态,
A1.LOT_CMF_15 面别,
A2.LOT_CMF_15 面别2,
A.TRAN_CODE AS "过账代码",
B.OPER_DESC AS "工序",
TO_CHAR(TO_DATE(A.TRAN_TIME,'YYYYMMDDHH24MISS'),'YYYY-MM-DD HH24:MI:SS') AS 过账时间,
D.USER_DESC AS "作业人",
C.TASK_ORDER AS "任务令",
A1.LOT_ID   AS  "背面板边条码",
A2.LOT_ID   AS  "正面板边条码"
FROM MWIPLOTHIS A
JOIN MWIPOPRDEF B ON A.factory  = B.FACTORY AND A.OLD_OPER=B.OPER
JOIN CWIPORDDEF C ON A.factory  = C.FACTORY AND A.ORDER_ID=C.ORDER_ID
JOIN MSECUSRDEF D ON A.factory  = D.FACTORY AND A.TRAN_USER_ID=D.USER_ID
LEFT JOIN MWIPLOTHIS A1 ON (A1.LOT_ID=A.LOT_CMF_13 AND A1.HIST_SEQ='1' AND (A1.LOT_CMF_15='B'OR A1.LOT_CMF_15='S' ))
LEFT JOIN MWIPLOTHIS A2 ON (A2.LOT_ID=A.LOT_CMF_14 AND A2.HIST_SEQ='1' AND A2.LOT_CMF_15='T')
WHERE A.FACTORY = NVL(TRIM('RCM1'),A.FACTORY)
AND A.HIST_DEL_FLAG = ' '
AND A.TRAN_CODE IN ('END','COLLECT_DFT')
AND A.LOT_CMF_20 = 'PCBA'
AND A.ORDER_ID = NVL(TRIM('FKFB180612J'),A.ORDER_ID)
AND A.LOT_ID = NVL(TRIM('FBFB18060MX0003227'),A.LOT_ID)
AND A.TRAN_TIME >= '20180627' || '08' || '30' || '00'
AND A.TRAN_TIME < '20180628' || '08' || '30' || '00'
