SELECT rownum rn9__, A.*  FROM ( SELECT ORDER_ID AS ORDER_ID , SUB_AREA AS SUB_AREA , SURFACE AS SURFACE , FAI_FLAG AS FAI_FLAG , TRAN_TIME AS TRAN_TIME , SYS_TRAN_TIME AS SYS_TRAN_TIME , TRAN_CODE AS TRAN_CODE , MAT_ID AS MAT_ID , MAT_VER AS MAT_VER , FLOW AS FLOW , FLOW_SEQ_NUM AS FLOW_SEQ_NUM , ORD_QTY AS ORD_QTY , RES_ID AS RES_ID , BOM_SET_VERSION AS BOM_SET_VERSION , CUSTOMER_ID AS CUSTOMER_ID , CUSTOMER_MAT_ID AS CUSTOMER_MAT_ID , WORK_DATE AS WORK_DATE , PLAN_START_TIME AS PLAN_START_TIME , PLAN_END_TIME AS PLAN_END_TIME , ORD_CMF_1 AS ORD_CMF_1 , ORD_CMF_2 AS ORD_CMF_2 , ORD_CMF_3 AS ORD_CMF_3 , ORD_CMF_4 AS ORD_CMF_4 , ORD_CMF_6 AS ORD_CMF_6 , ORD_CMF_7 AS ORD_CMF_7 , QTY AS QTY , LOT_TYPE AS LOT_TYPE , OWNER_CODE AS OWNER_CODE , CREATE_CODE AS CREATE_CODE , LOT_PRIORITY AS LOT_PRIORITY , ORG_DUE_TIME AS ORG_DUE_TIME , ORD_STATUS_FLAG AS ORD_STATUS_FLAG , ORD_IN_QTY AS ORD_IN_QTY , ORD_OUT_QTY AS ORD_OUT_QTY , ORD_LOSS_QTY AS ORD_LOSS_QTY , ORD_RWK_QTY AS ORD_RWK_QTY , TRAN_USER_ID AS TRAN_USER_ID
FROM (SELECT A.ORDER_ID,
(CASE
  WHEN A.LINE_ID = ' ' THEN ' '
  ELSE (SELECT T.DATA_1 FROM MGCMTBLDAT T WHERE T.TABLE_NAME = 'SUB_AREA' AND T.FACTORY = A.FACTORY AND T.KEY_1 = A.LINE_ID)
END) SUB_AREA,
A.SURFACE,
A.FAI_FLAG,
TO_CHAR(to_date(trim(A.TRAN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') TRAN_TIME,
TO_CHAR(to_date(trim(A.SYS_TRAN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') SYS_TRAN_TIME,
A.TRAN_CODE,
A.MAT_ID,
A.MAT_VER,
A.FLOW,
A.FLOW_SEQ_NUM,
A.ORD_QTY,
A.RES_ID,
A.BOM_SET_VERSION,
A.CUSTOMER_ID,
A.CUSTOMER_MAT_ID,
A.WORK_DATE,
A.PLAN_START_TIME,
A.PLAN_END_TIME,
A.ORD_CMF_1,
A.ORD_CMF_2,
A.ORD_CMF_3,
A.ORD_CMF_4,
A.ORD_CMF_6,
A.ORD_CMF_7,
A.QTY,
A.LOT_TYPE,
A.OWNER_CODE,
A.CREATE_CODE,
A.LOT_PRIORITY,
A.ORG_DUE_TIME,
A.ORD_STATUS_FLAG,
A.ORD_IN_QTY,
A.ORD_OUT_QTY,
A.ORD_LOSS_QTY,
A.ORD_RWK_QTY,
A.TRAN_USER_ID
FROM CWIPORDHIS A
WHERE A.FACTORY = trim( 'RCM1' )
AND (case
         when trim( 'FKFB180612J' ) is null then
1
         when trim( 'FKFB180612J' ) = A.ORDER_ID then
1
         else
0
       end) = 1
ORDER BY A.ORDER_ID) A
 ) A  WHERE ROWNUM < 10000
