WITH SMT_PROD_TEMP AS (
  select
         (CASE WHEN H.TRAN_TIME >= SUBSTR(H.TRAN_TIME,0,8)||'080000' THEN TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM-DD')
            ELSE TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS') -1,'YYYY-MM-DD')
          END
          )
          WORK_DATE,
         COUNT(DISTINCT H.LOT_ID) PROD_QTY
    from
    (SELECT /*+INDEX(H CWIPLOTMVH_IDX_3)*/
             H.FACTORY
            ,H.MAT_ID
            ,H.TRAN_TIME
            ,H.LOT_ID
    FROM CWIPLOTMVH H
    LEFT OUTER JOIN MGCMTBLDAT A
        ON A.FACTORY = H.FACTORY    AND A.KEY_1 = H.LINE_ID    AND A.TABLE_NAME = 'SUB_AREA'
    WHERE
            H.TRAN_TIME >= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW'),'YYYYMMDD') || '080000'
        AND H.TRAN_TIME <= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + 7,'YYYYMMDD') || '080000'
        AND (CASE WHEN H.BOARD_SIDE IN ( 'S',' ') AND H.TRAN_CODE IN ('END', 'COLLECT_DFT')
              THEN 1
            WHEN H.BOARD_SIDE IN ( 'T','B') AND H.TRAN_CODE IN ('CREATE','END', 'COLLECT_DFT')
              THEN 1
        END )  = 1
        AND H.ORDER_ID = NVL (TRIM (' '),H.ORDER_ID)
        AND H.FACTORY = 'RCM1'
        AND H.HIST_DEL_FLAG = ' '
        AND H.OLD_OPER = '120070'
        AND A.DATA_10 = 'DG'
        AND H.LINE_ID = '100050'
    ) H
      LEFT JOIN MWIPMATDEF D
          ON H.FACTORY = D.FACTORY    AND H.MAT_ID = D.MAT_ID
      WHERE 1=1
          AND D.MAT_CMF_1 IN(
            select DISTINCT KEY_1 from MGCMTBLDAT
            WHERE TABLE_NAME='PRODUCT_GRP'
              AND FACTORY = 'RCM1'
          AND KEY_1 = '20'
          )
    group by (CASE WHEN H.TRAN_TIME >= SUBSTR(H.TRAN_TIME,0,8)||'080000' THEN TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM-DD')
            ELSE TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS') -1,'YYYY-MM-DD')
          END
          )
  ),
  SMT_PLAN_TEMP AS (
    select
            TO_CHAR(TO_DATE(P.WORK_DATE,'YYYYMMDD'),'YYYY-MM-DD') WORK_DATE,
            SUM(P.PLAN_ORD_QTY) PLAN_QTY
    from CWIPORDPLN P
      LEFT JOIN MWIPMATDEF D
          ON P.FACTORY = D.FACTORY    AND P.MAT_ID = D.MAT_ID
    LEFT OUTER JOIN MGCMTBLDAT F
       ON F.FACTORY = P.FACTORY    AND F.KEY_1 = P.LINE_ID    AND F.TABLE_NAME = 'SUB_AREA'
      WHERE 1=1
      AND P.ORDER_ID = NVL (TRIM (' '),P.ORDER_ID)
      AND P.DELETE_FLAG = ' '
      AND D.MAT_CMF_1 IN(
        select DISTINCT KEY_1 from MGCMTBLDAT
        WHERE TABLE_NAME='PRODUCT_GRP'
          AND FACTORY = 'RCM1'
          AND KEY_1 = '20'
      )
      AND F.DATA_10 = 'DG'
      AND P.LINE_ID = '100050'
      and P.ORD_CMF_1 = 'SMT'
      and P.WORK_DATE >= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW'),'YYYYMMDD')
      and P.WORK_DATE <= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + 6,'YYYYMMDD')
    group by P.WORK_DATE
  ),
  SMT_WEEK_TEMP AS (
    SELECT '东莞SMT' T_TYPE,'东莞SMT' P_TYPE,to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + (level-1),'YYYY-MM-DD') WORK_DATE FROM DUAL
    connect by level <=7
  ),
  HD_PROD_TEMP AS (
  select T_TYPE,P_TYPE,WORK_DATE,COUNT(DISTINCT LOT_ID) PROD_QTY from(
    select
          C.DATA_2 T_TYPE,
      C.DATA_1 P_TYPE,
          (CASE WHEN H.TRAN_TIME >= SUBSTR(H.TRAN_TIME,0,8)||'080000' THEN TO_CHAR(to_date(H.TRAN_TIME,'YYYYMMDDHH24MISS'),'YYYY-MM-DD')
            ELSE TO_CHAR(to_date(H.TRAN_TIME,'YYYYMMDDHH24MISS') -1,'YYYY-MM-DD')
          END
          )
          WORK_DATE,
          H.LOT_ID
    FROM (
          SELECT /*+INDEX(H CWIPLOTMVH_IDX_3)*/
             H.FACTORY,
         H.TRAN_TIME,
         H.LOT_ID,
         H.MAT_ID
     from CWIPLOTMVH H
     LEFT OUTER JOIN (SELECT * FROM  MGCMTBLDAT WHERE FACTORY = 'RCM1' AND TABLE_NAME = 'SUB_AREA' AND DATA_10 = 'DG') A
      ON A.FACTORY = H.FACTORY AND A.KEY_1 = H.LINE_ID
      WHERE H.TRAN_TIME >= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW'),'YYYYMMDD') || '080000'
      AND H.TRAN_TIME <= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + 7,'YYYYMMDD') || '080000'
      AND H.TRAN_CODE IN('END','COLLECT _DFT')
      AND H.ORDER_ID = NVL (TRIM (' '),H.ORDER_ID)
      AND H.OLD_OPER = '180010'
      AND NVL(A.KEY_1,' ') != ' '
      AND H.HIST_DEL_FLAG = ' '
      AND H.FACTORY = 'RCM1'
      AND H.LINE_ID = '100050'
          ) H
      LEFT OUTER JOIN MWIPMATDEF D
          ON H.FACTORY = D.FACTORY    AND H.MAT_ID = D.MAT_ID
      LEFT OUTER JOIN (SELECT DISTINCT FACTORY,KEY_1,DATA_1,DATA_2 FROM MGCMTBLDAT WHERE TABLE_NAME = 'PRODUCT_GRP') C
          ON C.FACTORY = H.FACTORY    AND C.KEY_1 = D.MAT_CMF_1
      WHERE D.MAT_TYPE = (CASE WHEN H.MAT_ID IN ('1103-00036','1103-00046') THEN D.MAT_TYPE ELSE 'ZERT' END)
      AND C.KEY_1 = '20'
  )
  group by T_TYPE,P_TYPE,WORK_DATE
  ),
  HD_PLAN_TEMP AS (
    select T_TYPE,P_TYPE,WORK_DATE,SUM(PLAN_ORD_QTY) PLAN_QTY from(
      select  C.DATA_2 T_TYPE,
              C.DATA_1 P_TYPE,
              TO_CHAR(TO_DATE(P.WORK_DATE,'YYYYMMDD'),'YYYY-MM-DD') WORK_DATE,
              P.PLAN_ORD_QTY,
              P.ORD_CMF_1,
              P.LINE_ID,
              P.ORDER_ID
      from CWIPORDPLN P
        LEFT JOIN MWIPMATDEF D
          ON P.FACTORY = D.FACTORY    AND P.MAT_ID = D.MAT_ID
        LEFT OUTER JOIN (SELECT DISTINCT FACTORY,KEY_1,DATA_1,DATA_2 FROM MGCMTBLDAT WHERE TABLE_NAME = 'PRODUCT_GRP') C
          ON C.FACTORY = P.FACTORY    AND C.KEY_1 = D.MAT_CMF_1
        LEFT OUTER JOIN CWIPORDDEF E
         ON E.FACTORY = P.FACTORY     AND E.ORDER_ID = P.ORDER_ID AND E.PROD_ID = P.MAT_ID
        LEFT OUTER JOIN MGCMTBLDAT F
         ON F.TABLE_NAME = 'SUB_AREA' AND F.DATA_9 = E.CMF_5
      where 1=1
        AND P.ORDER_ID = NVL (TRIM (' '),P.ORDER_ID)
        AND P.DELETE_FLAG = ' '
        AND F.DATA_10 = 'DG'
        and P.ORD_CMF_1 = 'PAK'
        AND C.KEY_1 = '20'
        AND F.KEY_1 = '100050'
        and P.WORK_DATE >= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW'),'YYYYMMDD')
        and P.WORK_DATE <= to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + 6,'YYYYMMDD')
        )
    group by  T_TYPE,P_TYPE,WORK_DATE
  ),
  HD_WEEK_TEMP AS (
    SELECT B.DATA_2 T_TYPE,B.DATA_1 P_TYPE,A.WORK_DATE,0 PLAN_QTY,0 PROD_QTY,0 RATE FROM (
      SELECT to_char(TRUNC(to_date('20180627','YYYY-MM-DD HH24MISS'),'IW') + (level-1),'YYYY-MM-DD') WORK_DATE FROM DUAL
          connect by level <=7) A ,(
      SELECT DISTINCT DATA_2,DATA_1 FROM MGCMTBLDAT WHERE TABLE_NAME='PRODUCT_GRP'
        AND FACTORY =  'RCM1'
        AND DATA_2 in('PC内存','SV内存','SDT代工','企业级SSD','消费级SSD','安全产品')
        AND KEY_1 = '20'
      ) B
  )
SELECT * FROM
(select W.T_TYPE,W.P_TYPE,W.WORK_DATE,NVL(P.PLAN_QTY,0) PLAN_QTY,NVL(D.PROD_QTY,0) PROD_QTY,TO_CHAR(ROUND(NVL(D.PROD_QTY,0)/decode(NVL(P.PLAN_QTY,0),0,null,P.PLAN_QTY),4)*100,'99990.99') ||'%' AS RATE from SMT_WEEK_TEMP W
  left join SMT_PROD_TEMP D ON W.WORK_DATE = D.WORK_DATE
  left join SMT_PLAN_TEMP P ON W.WORK_DATE = P.WORK_DATE
union all
select W.T_TYPE,W.P_TYPE,'周汇总' WORK_DATE,NVL(SUM(P.PLAN_QTY),0) PLAN_QTY,NVL(SUM(D.PROD_QTY),0) PROD_QTY,TO_CHAR(ROUND(NVL(SUM(D.PROD_QTY),0)/decode(NVL(SUM(P.PLAN_QTY),0),0,null,SUM(P.PLAN_QTY)),4)*100,'99990.99') ||'%' AS RATE from SMT_WEEK_TEMP W
  left join SMT_PROD_TEMP D ON W.WORK_DATE = D.WORK_DATE
  left join SMT_PLAN_TEMP P ON W.WORK_DATE = P.WORK_DATE
  group by W.T_TYPE,W.P_TYPE
union all
select '后段' || W1.T_TYPE,W1.P_TYPE,W1.WORK_DATE,NVL(P1.PLAN_QTY,0) PLAN_QTY,NVL(D1.PROD_QTY,0) PROD_QTY,TO_CHAR(ROUND(NVL(D1.PROD_QTY,0)/decode(NVL(P1.PLAN_QTY,0),0,null,P1.PLAN_QTY),4)*100,'99990.99') ||'%' AS RATE from HD_WEEK_TEMP W1
  left join HD_PROD_TEMP D1 ON W1.WORK_DATE = D1.WORK_DATE AND W1.P_TYPE = D1.P_TYPE
  left join HD_PLAN_TEMP P1 ON W1.WORK_DATE = P1.WORK_DATE AND W1.P_TYPE = P1.P_TYPE
union all
select '后段' || W1.T_TYPE,W1.P_TYPE,'周汇总' WORK_DATE,NVL(SUM(P1.PLAN_QTY),0) PLAN_QTY,NVL(SUM(D1.PROD_QTY),0) PROD_QTY,TO_CHAR(ROUND(NVL(SUM(D1.PROD_QTY),0)/decode(NVL(SUM(P1.PLAN_QTY),0),0,null,SUM(P1.PLAN_QTY)),4)*100,'99990.99') ||'%' AS RATE from HD_WEEK_TEMP W1
  left join HD_PROD_TEMP D1 ON W1.WORK_DATE = D1.WORK_DATE AND W1.P_TYPE = D1.P_TYPE
  left join HD_PLAN_TEMP P1 ON W1.WORK_DATE = P1.WORK_DATE AND W1.P_TYPE = P1.P_TYPE
  group by W1.T_TYPE,W1.P_TYPE
) A
WHERE A.PLAN_QTY + A.PROD_QTY <> 0
order by 3,1
