SELECT rownum rn9__, A.*  FROM ( SELECT MAT_GROUP AS MAT_GROUP , MAT_GROUP_DESC AS MAT_GROUP_DESC , GOOD_QTY AS GOOD_QTY , BAD_QTY AS BAD_QTY , GOOD_RATE AS GOOD_RATE
FROM (SELECT
MAT_GROUP,
MAT_GROUP_DESC,
SUM(GOOD_QTY) AS GOOD_QTY,
SUM(BAD_QTY) AS BAD_QTY,
CASE WHEN  SUM(BAD_QTY) = 0 THEN 100
        WHEN SUM(GOOD_QTY) = 0 THEN 0
        ELSE ROUND(SUM(GOOD_QTY)/(SUM(GOOD_QTY) + SUM(BAD_QTY)),4)* 100   END AS GOOD_RATE
FROM CWIPSUMSTS
GROUP BY
    MAT_GROUP,
    MAT_GROUP_DESC
ORDER BY MAT_GROUP) A
 ) A  WHERE ROWNUM < 10000
