WITH DEF AS(
SELECT WORK_DATE,LINE_ID,ORDER_ID,OPER OLD_OPER,LOT_CMF_2 STATUS,COUNT(DISTINCT LOT_ID) AS QTY FROM
 ( SELECT A.FACTORY,B.ORDER_ID, A.LOT_ID, A.HIST_SEQ,B.LOT_CMF_2,B.HIST_DEL_FLAG,G.PRODUCT_GRP,J.DATA_2 PRODUCT_DESC, A.OPER, H.OPER_SHORT_DESC, A.TRAN_TIME, C.LINE_ID, C.DEFECT_TYPE, C.DEFECT_CODE, C.DEFECT_LOCATION, E.DATA_8,E.DATA_10, F.DATA_5 Yield_DEL_Flag, F.DATA_2 DEFECT_NAME, F.DATA_6 Yield_type,(CASE
WHEN E.DATA_10 = 'DG' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '080000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
             WHEN E.DATA_10 = 'DG' AND SUBSTR(A.TRAN_TIME, 9, 6) < '080000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
             WHEN E.DATA_10 = 'HY' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '083000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
             WHEN E.DATA_10 = 'HY' AND SUBSTR(A.TRAN_TIME, 9, 6) < '083000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
             ELSE              'NA'         END) WORK_DATE
  FROM   MWIPLOTDFT A, MWIPLOTHIS B, CWIPDFTEXT C, MGCMTBLDAT E, (SELECT KEY_1, KEY_2, KEY_3, KEY_4, DATA_2, DATA_5, DATA_6 FROM MGCMTBLDAT WHERE FACTORY='RCM1' AND  TABLE_NAME = 'OPER_DEFECT_CODE') F, CWIPORDDEF G, MWIPOPRDEF H,
  (SELECT FACTORY, KEY_1, DATA_2 FROM MGCMTBLDAT WHERE FACTORY='RCM1' AND TABLE_NAME = 'PRODUCT_GRP' ) J
  WHERE  A.FACTORY = 'RCM1' AND A.TRAN_TIME >= TO_CHAR(SYSDATE - 7, 'YYYYMMDD') || '080000' AND A.TRAN_TIME < TO_CHAR(SYSDATE, 'YYYYMMDD') || '083000' AND  B.HIST_DEL_FLAG = ' '
         AND A.FACTORY = B.FACTORY AND A.LOT_ID = B.LOT_ID AND B.HIST_SEQ = A.HIST_SEQ AND B.HIST_DEL_FLAG = ' ' AND C.LINE_ID = E.KEY_1 AND E.TABLE_NAME = 'SUB_AREA' AND A.FACTORY = E.FACTORY
         AND A.LOT_ID = C.LOT_ID AND A.SUBLOT_ID = C.SUBLOT_ID AND A.HIST_SEQ = C.HIST_SEQ AND A.SEQ_NUM = C.SEQ_NUM AND B.FACTORY = G.FACTORY AND B.ORDER_ID = G.ORDER_ID
         AND A.FACTORY = H.FACTORY AND A.OPER = H.OPER AND G.PRODUCT_GRP = F.KEY_1 AND H.OPER_SHORT_DESC = F.KEY_2 AND C.DEFECT_TYPE = F.KEY_3 AND C.DEFECT_CODE = F.KEY_4
         AND G.PRODUCT_GRP=J.KEY_1 )
         GROUP BY WORK_DATE,LINE_ID,ORDER_ID,OPER,LOT_CMF_2),
PROG_NG_TEMP AS(
  SELECT A.WORK_DATE, E.OPER_SHORT_DESC OPER, C.DATA_2, D.DATA_8, SUM(A.QTY) AS NG_QTY
  FROM   DEF A, CWIPORDDEF B, MGCMTBLDAT C, MGCMTBLDAT D, MWIPOPRDEF E
  WHERE  A.ORDER_ID = B.ORDER_ID AND SUBSTR(A.ORDER_ID, 2, 1) NOT IN ('K') AND B.FACTORY = 'RCM1' AND C.TABLE_NAME = 'PRODUCT_GRP' AND B.PRODUCT_GRP = C.KEY_1 AND C.FACTORY = 'RCM1' AND
         D.TABLE_NAME = 'SUB_AREA' AND A.LINE_ID = D.KEY_1 AND D.FACTORY = 'RCM1' AND A.STATUS IN ('NG') AND E.FACTORY = 'RCM1' AND E.OPER_CMF_7 = 'Y' AND A.OLD_OPER = E.OPER
  GROUP  BY A.WORK_DATE, E.OPER_SHORT_DESC, C.DATA_2, D.DATA_8),
PROG_IN_TEMP AS
 ( SELECT A.WORK_DATE, E.OPER_SHORT_DESC OPER, C.DATA_2, D.DATA_8, SUM(A.QTY) AS IN_QTY
   FROM ( SELECT /*+INDEX(H CWIPLOTMVH_IDX_3)*/
            (CASE WHEN SUBSTR(A.LINE_ID, 1, 2) = '10' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '080000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
                  WHEN SUBSTR(A.LINE_ID, 1, 2) = '10' AND SUBSTR(A.TRAN_TIME, 9, 6) < '080000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
                  WHEN SUBSTR(A.LINE_ID, 1, 2) = '20' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '083000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
                  WHEN SUBSTR(A.LINE_ID, 1, 2) = '20' AND SUBSTR(A.TRAN_TIME, 9, 6) < '083000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
                  ELSE  'NA' END) WORK_DATE, A.LINE_ID, A.ORDER_ID, A.OLD_OPER, A.STATUS, COUNT(DISTINCT A.LOT_ID) QTY
           FROM   CWIPLOTMVH A
           WHERE  A.FACTORY = 'RCM1' AND A.TRAN_TIME >= TO_CHAR(SYSDATE - 7, 'YYYYMMDD') || '080000' AND A.TRAN_TIME < TO_CHAR(SYSDATE, 'YYYYMMDD') || '083000' AND
                  A.TRAN_CODE IN ('END', 'SKIP', 'COLLECT_DFT') AND A.HIST_DEL_FLAG = ' '
           GROUP  BY (CASE  WHEN SUBSTR(A.LINE_ID, 1, 2) = '10' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '080000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
                            WHEN SUBSTR(A.LINE_ID, 1, 2) = '10' AND SUBSTR(A.TRAN_TIME, 9, 6) < '080000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
                            WHEN SUBSTR(A.LINE_ID, 1, 2) = '20' AND SUBSTR(A.TRAN_TIME, 9, 6) >= '083000' THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS'), 'YYYY-MM-DD')
                            WHEN SUBSTR(A.LINE_ID, 1, 2) = '20' AND SUBSTR(A.TRAN_TIME, 9, 6) < '083000'  THEN  TO_CHAR(TO_DATE(A.TRAN_TIME, 'YYYY-MM-DD HH24MISS') - 1, 'YYYY-MM-DD')
                            ELSE  'NA' END), A.LINE_ID, A.ORDER_ID, A.OLD_OPER, A.STATUS) A, CWIPORDDEF B, MGCMTBLDAT C, MGCMTBLDAT D, MWIPOPRDEF E
  WHERE  A.ORDER_ID = B.ORDER_ID AND B.FACTORY = 'RCM1' AND SUBSTR(A.ORDER_ID, 2, 1) NOT IN ('K') AND C.TABLE_NAME = 'PRODUCT_GRP' AND B.PRODUCT_GRP = C.KEY_1 AND C.FACTORY = 'RCM1' AND
         D.TABLE_NAME = 'SUB_AREA' AND A.LINE_ID = D.KEY_1 AND D.FACTORY = 'RCM1' AND A.STATUS IN ('OK', 'NG') AND E.FACTORY = 'RCM1' AND E.OPER_CMF_7 = 'Y' AND A.OLD_OPER = E.OPER
  GROUP  BY A.WORK_DATE, E.OPER_SHORT_DESC, C.DATA_2, D.DATA_8),
WEEK_TMEP AS
 (SELECT ROWNUM AS SEQ, TO_CHAR(TO_DATE('20180621' + ROWNUM - 1,'YYYYMMDD'),'YYYY-MM-DD') AS WORK_DATE FROM DUAL CONNECT BY ROWNUM <= '20180628'-'20180621'+1),
TAL_PROD AS(
SELECT DATA_8, DATA_2, A.WORK_DATE, OPER, IN_QTY "投入数", NG_QTY "不良数", TOTAL "工序良率", SEQ
  FROM   (SELECT A.WORK_DATE, A.OPER, A.DATA_2, A.DATA_8, A.IN_QTY, NVL(B.NG_QTY, 0) NG_QTY,
           TRUNC(1 -NVL(B.NG_QTY ,0) / DECODE(NVL(A.IN_QTY ,0),0,NULL,A.IN_QTY),6) TOTAL
           FROM   PROG_IN_TEMP A
LEFT   JOIN PROG_NG_TEMP B
           ON     (A.WORK_DATE = B.WORK_DATE AND A.OPER = B.OPER AND A.DATA_2 = B.DATA_2 AND A.DATA_8 = B.DATA_8)
           GROUP  BY A.WORK_DATE, A.OPER, A.DATA_2, A.DATA_8, A.IN_QTY, B.NG_QTY) A, WEEK_TMEP C
  WHERE  A.WORK_DATE = C.WORK_DATE),
TOTAL_Yield AS (
SELECT DISTINCT WORK_DATE,DATA_8, DATA_2, SEQ, 'ALL' OPER, 0 投入数, 0 不良数, EXP(SUM(lN(工序良率)) over(partition by DATA_8, DATA_2, SEQ order by DATA_8, DATA_2, SEQ)) 总体直通率
  FROM   TAL_PROD
  WHERE  工序良率 <> '0'
  ORDER BY SEQ)
,STANED AS
 ( SELECT WORK_DATE,KEY_1, KEY_2, 'ALL' OPER, DATA_1 AS TARGET
  FROM   (SELECT A.WORK_DATE, B.KEY_1, B.KEY_2,B.DATA_1
           FROM   WEEK_TMEP A, (SELECT KEY_1, KEY_2, KEY_3, DATA_1 FROM MGCMLAGDAT WHERE TABLE_NAME = 'DATE_CODE') B
           WHERE  SUBSTR(REPLACE(A.WORK_DATE, '-', ''), 1, 6) = B.KEY_3)) ,
PRO_TOTAL AS (
           SELECT WORK_DATE,DATA_8, DATA_2, SEQ, OPER, 投入数, 不良数, 工序良率 AS GOOD_RATE FROM TAL_PROD
           UNION ALL
           SELECT WORK_DATE,DATA_8, DATA_2, SEQ, OPER, 投入数, 不良数, 总体直通率 FROM TOTAL_Yield)
SELECT
        A.WORK_DATE AS 日期,
        A.DATA_8 AS 工厂,
        A.DATA_2 AS 产品组,
        LTRIM(TO_CHAR(TRUNC(A.GOOD_RATE * 100,3),'999.99')) AS 总体直通率,
        LTRIM(TO_CHAR(B.TARGET, '999.99')) AS 直通率目标
FROM   PRO_TOTAL A,STANED B
WHERE  A.OPER = B.OPER
AND A.DATA_2 = B.KEY_2
AND A.DATA_8 = B.KEY_1
AND A.WORK_DATE = B.WORK_DATE
AND A.OPER = 'ALL'
AND A.DATA_8 = NVL(TRIM('东莞'),A.DATA_8)
AND A.DATA_2 = '消费级SSD'
