SELECT
WORK_DATE, AREA, WORK_SHOP, USER_ID, USER_DESC, ENTER_DATE ,WORK_LIFE,DIR_EFF,COM_EFF,IS_JOB
FROM
(
SELECT A.WORK_DATE, A.AREA, A.WORK_SHOP,A.USER_ID, A.USER_DESC, B.ENTER_DATE ,
DECODE(B.ENTER_DATE ,' ',0, TRUNC(MONTHS_BETWEEN(SYSDATE,TO_DATE(B.ENTER_DATE, 'YYYYMMDD'))/12,1))  WORK_LIFE ,
A.DIR_EFF, A.COM_EFF,
DECODE(B.EXPIRE_DATE,'99981231','Y','N') IS_JOB
FROM USER_EFF A, MSECUSRDEF B
WHERE 1=1
AND B.FACTORY = 'RCM1'
AND A.USER_ID = B.USER_ID
AND 1 = (CASE WHEN A.WORK_SHOP = 'SMT' AND A.COM_EFF > '95' THEN 1 WHEN A.WORK_SHOP = '后段' AND A.COM_EFF > '100' THEN 1 ELSE 0 END)
AND A.AREA = 'DG-SSD'
AND A.WORK_SHOP = NVL (TRIM ('SMT'),A.WORK_SHOP)
AND A.USER_ID = NVL (TRIM (' '),A.USER_ID)
AND A.WORK_DATE >= '20180624'
AND A.WORK_DATE <= '20180630'
ORDER BY WORK_DATE, AREA, WORK_SHOP, COM_EFF DESC
)
