WITH A AS
(
   SELECT DECODE(SIGN(SUBSTR(C.ON_TIME,9,6)-074000),1,SUBSTR(C.ON_TIME,0,8),0,SUBSTR(C.ON_TIME,0,8),TO_CHAR(TO_DATE(SUBSTR(C.ON_TIME,0,8),'YYYYMMDD')-1,'YYYYMMDD')) WORK_DATE
         ,C.AREA
         ,C.USER_ID
         ,USR.USER_DESC
         ,C.OPER
         ,OPR.OPER_DESC
         ,C.ON_TIME
         ,C.OFF_TIME
         ,C.STATUS
    FROM CSECUSRONO C ,
         MSECUSRDEF USR,
         MWIPOPRDEF OPR
    WHERE C.USER_ID IN (
           SELECT USER_ID FROM
            (
              SELECT AREA,USER_ID,SUM(1)-1 CH_QTY FROM
              (
                SELECT DISTINCT(A.OPER),A.AREA,A.USER_ID
                FROM CSECUSRONO A
                WHERE 1=1
                AND A.FACTORY = 'RCM1'
                AND A.ON_TIME >= '20180624'||'074000'
                AND A.ON_TIME <  TO_CHAR(TO_DATE('20180628','YYYYMMDD')+1,'YYYYMMDD')||'074000'
                AND A.AREA IN('DG-SSD','DG-SDT','HY-MEM')
              )
              GROUP BY AREA,USER_ID
            )
            WHERE CH_QTY > 0
            GROUP BY USER_ID
    )
    AND C.FACTORY = 'RCM1'
    AND USR.FACTORY = 'RCM1'
    AND OPR.FACTORY = 'RCM1'
    AND C.USER_ID = USR.USER_ID
    AND C.OPER = OPR.OPER
    AND C.AREA IN('DG-SSD','DG-SDT','HY-MEM')
    AND C.AREA = NVL(TRIM('DG-SSD'),C.AREA)
    AND C.USER_ID = NVL(TRIM(' '),C.USER_ID)
    AND C.ON_TIME >= '20180624'||'074000'
    AND C.ON_TIME <  TO_CHAR(TO_DATE('20180628','YYYYMMDD')+1,'YYYYMMDD')||'074000'
),B AS
(
  SELECT WORK_DATE,AREA,USER_ID ,CH_QTY FROM
  (
    SELECT WORK_DATE,AREA,USER_ID,SUM(1)-1 CH_QTY FROM
    (
      SELECT
              DISTINCT(A.OPER),
              DECODE(SIGN(SUBSTR(A.ON_TIME,9,6)-074000),1,SUBSTR(A.ON_TIME,0,8),0,SUBSTR(A.ON_TIME,0,8),TO_CHAR(TO_DATE(SUBSTR(A.ON_TIME,0,8),'YYYYMMDD')-1,'YYYYMMDD')) WORK_DATE,
              A.AREA,
              A.USER_ID
      FROM CSECUSRONO A
      WHERE 1=1
      AND A.FACTORY = 'RCM1'
      AND A.AREA IN('DG-SSD','DG-SDT','HY-MEM')
      AND A.AREA = NVL(TRIM('DG-SSD'),A.AREA)
      AND A.USER_ID = NVL(TRIM(' '),A.USER_ID)
      AND A.ON_TIME >= '20180624'||'074000'
      AND A.ON_TIME <  TO_CHAR(TO_DATE('20180628','YYYYMMDD')+1,'YYYYMMDD')||'074000'
    )
    GROUP BY WORK_DATE,AREA ,USER_ID
  )
  WHERE CH_QTY > 0
)
SELECT A.WORK_DATE ,A.AREA ,A.USER_ID,A.USER_DESC,A.OPER_DESC,
TO_CHAR(TO_DATE(A.ON_TIME,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS') ON_TIME,
DECODE (A.OFF_TIME ,' ', ' ', TO_CHAR(TO_DATE(A.OFF_TIME,'YYYY-MM-DD HH24:MI:SS'),'YYYY-MM-DD HH24:MI:SS')) OFF_TIME,
A.STATUS,B.CH_QTY
FROM A,B
WHERE 1=1
AND A.AREA = B.AREA(+)
AND A.USER_ID = B.USER_ID(+)
AND A.WORK_DATE = B.WORK_DATE(+)
ORDER BY WORK_DATE ,AREA,USER_ID,ON_TIME DESC
