WITH PCB_INFO AS (
    SELECT
            DECODE(SIGN(SUBSTR(H.CREATE_TIME,9,6)-080000),1,SUBSTR(H.CREATE_TIME,0,8),0,SUBSTR(H.CREATE_TIME,0,8),TO_CHAR(TO_DATE(SUBSTR(H.CREATE_TIME,0,8),'YYYYMMDD')-1,'YYYYMMDD')) AS WORK_DATE,
            A.DATA_2 AS AREA,
            'SMT' AS WORK_SHOP,
            H.PCBA_ID,
            H.AB_SUBFACE
    FROM CWIPVIPCBA H,MGCMTBLDAT A
    WHERE 1=1
    AND H.FACTORY = A.FACTORY(+)
    AND H.LINE_ID = A.KEY_1(+)
    AND H.FACTORY = 'RCM1'
    AND A.DATA_10 = 'DG'
    AND A.TABLE_NAME = 'SUB_AREA'
    AND H.CREATE_TIME >= '20180627' || '080000'
    AND H.CREATE_TIME < TO_CHAR(TO_DATE('20180628','YYYYMMDD')+1,'YYYYMMDD') || '080000'
    ),
SMT_PROD AS (
    SELECT WORK_DATE,WORK_SHOP,AREA,SUM(PROD_QTY) PROD_QTY FROM (
          SELECT WORK_DATE,WORK_SHOP,AREA,SUM(PROD_QTY)/2 PROD_QTY FROM(
            SELECT WORK_DATE,WORK_SHOP,AREA,COUNT(DISTINCT PCBA_ID) PROD_QTY FROM PCB_INFO
                WHERE AB_SUBFACE = 'T'
                  AND WORK_DATE >= '20180627'
                  AND WORK_DATE <= TO_CHAR(TO_DATE('20180628','YYYYMMDD') + 1,'YYYYMMDD')
                GROUP BY WORK_DATE,WORK_SHOP,AREA
            UNION ALL
            SELECT WORK_DATE,WORK_SHOP,AREA,COUNT(DISTINCT PCBA_ID) PROD_QTY FROM PCB_INFO
                WHERE AB_SUBFACE = 'B'
                  AND WORK_DATE >= '20180627'
                  AND WORK_DATE <= TO_CHAR(TO_DATE('20180628','YYYYMMDD') + 1,'YYYYMMDD')
                GROUP BY WORK_DATE,WORK_SHOP,AREA
            )
            GROUP BY WORK_DATE,WORK_SHOP,AREA
          UNION ALL
            SELECT WORK_DATE,WORK_SHOP,AREA,COUNT(DISTINCT PCBA_ID) PROD_QTY FROM PCB_INFO
                WHERE AB_SUBFACE = 'S'
                  AND WORK_DATE >= '20180627'
                  AND WORK_DATE <= TO_CHAR(TO_DATE('20180628','YYYYMMDD') + 1,'YYYYMMDD')
                GROUP BY WORK_DATE,WORK_SHOP,AREA
    )
    GROUP BY WORK_DATE,WORK_SHOP,AREA
),
PLAN AS(
    SELECT WORK_DATE,WORK_SHOP,AREA,SUM(PLAN_ORD_QTY) PLAN_QTY FROM(
      SELECT
             P.WORK_DATE,
             DECODE(P.ORD_CMF_1,'PAK','后段',P.ORD_CMF_1) AS WORK_SHOP,
             A.DATA_2 AS AREA,
             P.PLAN_ORD_QTY
      FROM CWIPORDPLN P,MGCMTBLDAT A
      WHERE 1=1
        AND P.FACTORY = A.FACTORY(+)
        AND P.LINE_ID = A.KEY_1(+)
        AND P.FACTORY = 'RCM1'
        AND A.DATA_10 = 'DG'
        AND A.TABLE_NAME = 'SUB_AREA'
        AND P.DELETE_FLAG = ' '
        AND P.WORK_DATE >= '20180627'
        AND P.WORK_DATE <= TO_CHAR(TO_DATE('20180628','YYYYMMDD') + 1,'YYYYMMDD')
    )
    GROUP BY WORK_DATE,WORK_SHOP,AREA
),
HD_PROD AS(
    SELECT WORK_DATE,WORK_SHOP,AREA,COUNT(DISTINCT LOT_ID) PROD_QTY FROM(
          SELECT
                DECODE(SIGN(SUBSTR(H.TRAN_TIME,9,6)-080000),1,SUBSTR(H.TRAN_TIME,0,8),0,SUBSTR(H.TRAN_TIME,0,8),TO_CHAR(TO_DATE(SUBSTR(H.TRAN_TIME,0,8),'YYYYMMDD')-1,'YYYYMMDD')) AS WORK_DATE,
                '后段' WORK_SHOP,
                A.DATA_2 AS AREA,
                H.LOT_ID
          FROM CWIPLOTMVH H
          LEFT OUTER JOIN MWIPMATDEF D ON H.FACTORY = D.FACTORY AND H.MAT_ID = D.MAT_ID
          LEFT OUTER JOIN MGCMTBLDAT A ON H.FACTORY = A.FACTORY AND H.LINE_ID = A.KEY_1 AND A.TABLE_NAME = 'SUB_AREA'
          WHERE H.TRAN_TIME >= '20180627' || '080000'
            AND H.TRAN_TIME <  TO_CHAR(TO_DATE('20180628','YYYYMMDD') + 1,'YYYYMMDD')  || '080000'
            AND H.TRAN_CODE IN ( 'END','COLLECT_DFT')
            AND H.HIST_DEL_FLAG = ' '
            AND H.FACTORY = 'RCM1'
            AND D.MAT_CMF_1 IN( SELECT DISTINCT KEY_1 FROM MGCMTBLDAT WHERE TABLE_NAME='PRODUCT_GRP' AND FACTORY = 'RCM1')
            AND A.DATA_10 = 'DG'
            AND H.OLD_OPER = '180010'
            AND D.MAT_TYPE = (CASE WHEN H.MAT_ID IN ('1103-00036','1103-00046') THEN D.MAT_TYPE ELSE 'ZERT' END)
            )
    GROUP BY WORK_DATE,WORK_SHOP,AREA
),
DAY AS (
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'SMT' AS WORK_SHOP,'DG-SSD' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
    UNION ALL
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'SMT' AS WORK_SHOP,'DG-SDT' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
    UNION ALL
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'SMT' AS WORK_SHOP,'DG-MEM' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
    UNION ALL
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'后段' AS WORK_SHOP,'DG-SSD' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
    UNION ALL
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'后段' AS WORK_SHOP,'DG-SDT' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
    UNION ALL
    SELECT ROWNUM,'20180627'+ROWNUM-1 AS WORK_DATE,'后段' AS WORK_SHOP,'DG-MEM' AS AREA FROM DUAL
        CONNECT BY ROWNUM <= '20180628'-'20180627' +1
)
SELECT * FROM (
    --SMT
    SELECT
            A.WORK_DATE,
            A.WORK_SHOP,
            A.AREA,
            NVL(P.PLAN_QTY,0) AS PLAN_QTY,
            NVL(D.PROD_QTY,0) AS PROD_QTY,
            P.PLAN_QTY-D.PROD_QTY AS DIFFER,
            TO_CHAR(ROUND(NVL(D.PROD_QTY,0)/decode(NVL(P.PLAN_QTY,0),0,null,P.PLAN_QTY),4)*100,'99990.99')  AS YIELD_RATE
    FROM DAY A, PLAN P, SMT_PROD D
    WHERE 1=1
    AND A.WORK_DATE = P.WORK_DATE(+)
    AND A.WORK_SHOP = P.WORK_SHOP(+)
    AND A.AREA = P.AREA(+)
    AND A.WORK_DATE = D.WORK_DATE(+)
    AND A.WORK_SHOP = D.WORK_SHOP(+)
    AND A.AREA = D.AREA(+)
    AND A.WORK_SHOP = 'SMT'
    --PAK
    UNION ALL
    SELECT
            A.WORK_DATE,
            A.WORK_SHOP,
            A.AREA,
            NVL(P.PLAN_QTY,0) AS PLAN_QTY,
            NVL(D.PROD_QTY,0) AS PROD_QTY,
            P.PLAN_QTY-D.PROD_QTY AS DIFFER,
            TO_CHAR(ROUND(NVL(D.PROD_QTY,0)/decode(NVL(P.PLAN_QTY,0),0,null,P.PLAN_QTY),4)*100,'99990.99')  AS YIELD_RATE
    FROM DAY A, PLAN P, HD_PROD D
    WHERE 1=1
    AND A.WORK_DATE = P.WORK_DATE(+)
    AND A.WORK_SHOP = P.WORK_SHOP(+)
    AND A.AREA = P.AREA(+)
    AND A.WORK_DATE = D.WORK_DATE(+)
    AND A.WORK_SHOP = D.WORK_SHOP(+)
    AND A.AREA = D.AREA(+)
    AND A.WORK_SHOP = '后段'
)
WHERE 1=1
AND WORK_SHOP = NVL(TRIM(' '),WORK_SHOP)
ORDER BY WORK_DATE,WORK_SHOP,AREA
