SELECT
A.*,
DECODE(A.STAN_QTY,' ',0,A.STAN_QTY)- A.GOOD_QTY  AS DIFF_QTY
FROM(
SELECT
    MAT_GROUP_DESC,
    OPER_DESC,
    ' ' AS STAN_QTY,
    GOOD_QTY,
    BAD_QTY,
    CASE WHEN  BAD_QTY = 0 THEN 100
        WHEN GOOD_QTY + BAD_QTY = 0  THEN 100
        ELSE ROUND(GOOD_QTY/(GOOD_QTY + BAD_QTY),4) * 100   END AS GOOD_RATE
FROM CWIPSUMSTS
WHERE 1=1
AND MAT_GROUP = '20'
ORDER BY MAT_GROUP,OPER) A
