WITH  A AS
(
  SELECT TO_CHAR(TO_DATE('20180520','YYYYMMDD')+RN,'YYYYMMDD')WORK_DATE FROM (SELECT ROWNUM-1 RN FROM DUAL CONNECT BY ROWNUM<=1000)
 WHERE TO_CHAR(TO_DATE('20180520','YYYYMMDD')+RN,'YYYYMMDD') BETWEEN '20180520' AND '20180522' --界面时间段
),
B AS
(
     SELECT WORK_DATE ,PROD_GRP,T_QTY ACT_COUNT,SUM(C_STA_TIME) STA_TIME FROM
     (
         SELECT WORK_DATE,PROD_GRP,MAT_ID ,QTY,STA_TIME,T_QTY, TRUNC((QTY/T_QTY*STA_TIME),2) C_STA_TIME  FROM
         (
         SELECT PRD.WORK_DATE ,GRP.DATA_1 PROD_GRP,PRD.MAT_ID, SUM(PRD.TRAN_COUNT) QTY,MAX(GCM.STA_TIME)STA_TIME,T.T_QTY
         FROM CWIPPRDSUM PRD, MWIPMATDEF MAT ,
            (SELECT KEY_2 MAT_ID, SUM(DATA_6) STA_TIME FROM MGCMTBLDAT WHERE FACTORY = 'RCM1' AND TABLE_NAME = 'C_LABOR_OPER' AND DATA_5 = ' ' GROUP BY KEY_2 ) GCM,
            (SELECT WORK_DATE , MAT.MAT_CMF_1 PRODUCT_GRP,SUM(TRAN_COUNT) T_QTY FROM CWIPPRDSUM PRD,MWIPMATDEF MAT
                WHERE 1=1
                AND PRD.FACTORY = 'RCM1' AND MAT.FACTORY = 'RCM1'
                AND PRD.MAT_ID = MAT.MAT_ID
--                AND MAT.MAT_CMF_1 in ('20','21')   --产品组条件
                AND OPER ='180010'
                GROUP BY  WORK_DATE ,MAT.MAT_CMF_1 ORDER BY WORK_DATE
            )T,
            (SELECT KEY_1,DATA_1 FROM MGCMTBLDAT WHERE FACTORY = 'RCM1' AND TABLE_NAME = 'PRODUCT_GRP') GRP
            WHERE 1=1
            AND PRD.FACTORY = 'RCM1'
            AND MAT.FACTORY = 'RCM1'
            AND PRD.MAT_ID = MAT.MAT_ID
            AND PRD.MAT_ID = GCM.MAT_ID
            AND GRP.KEY_1 = MAT.MAT_CMF_1
            AND GRP.KEY_1 = T.PRODUCT_GRP
--              AND MAT.MAT_CMF_1 in ('20','21')
            AND MAT.MAT_TYPE = 'ZERT'
            AND PRD.OPER = '180010'
            AND PRD.WORK_DATE = T.WORK_DATE
            GROUP BY PRD.WORK_DATE ,GRP.DATA_1,PRD.MAT_ID ,T.T_QTY ORDER BY PRD.WORK_DATE
            )
     )GROUP BY WORK_DATE ,PROD_GRP,T_QTY ORDER BY WORK_DATE
),
C AS
(
    SELECT ACT.WORK_DATE , GRP.DATA_1 PROD_GRP, TRUNC(SUM(ACT.ATT_TIME)/60,2) ACT_TIME  FROM CWIPACTTME ACT, CWIPMATEXT EXT,
    (SELECT KEY_1,DATA_1 FROM MGCMTBLDAT WHERE FACTORY = 'RCM1' AND TABLE_NAME = 'PRODUCT_GRP') GRP
      WHERE 1=1
      AND EXT.FACTORY = 'RCM1'
      AND ACT.MAT_ID = EXT.MAT_ID
      AND ACT.PRODUCT_GRP = GRP.KEY_1
      AND ACT.DELETE_FLAG != 'Y'
--        AND ACT.PRODUCT_GRP in ('20','21')
      GROUP BY WORK_DATE,GRP.DATA_1
      ORDER BY WORK_DATE,ACT_TIME
)
SELECT A.WORK_DATE,DECODE(B.PROD_GRP,NULL,C.PROD_GRP,B.PROD_GRP)PROD_GRP,
B.ACT_COUNT,C.ACT_TIME,B.STA_TIME,
TRUNC(NVL(B.ACT_COUNT/C.ACT_TIME,0),2) ACT_UPPH ,
TRUNC(NVL(3600/B.STA_TIME,0),2)STA_UPPH,
DECODE(NVL(3600/B.STA_TIME,0),0,0,TRUNC(NVL(TRUNC(NVL(B.ACT_COUNT/C.ACT_TIME,0),2)/TRUNC(NVL(3600/B.STA_TIME,0),2),0),2))UPPH_RATE
FROM A ,B ,C
WHERE 1=1
AND A.WORK_DATE = B.WORK_DATE(+)
AND A.WORK_DATE = C.WORK_DATE(+)
AND B.PROD_GRP = C.PROD_GRP
ORDER BY A.WORK_DATE
