SELECT
        TO_CHAR( to_date(WORK_DATE,'yyyy-mm-dd'),'yyyy-mm-dd' ) WORK_DATE,
        AREA,
        WORK_SHOP,
        100 AS STA_DIR_EFF,
        MAX(DIR_EFF) AS ACT_DIR_EFF,
        (CASE WHEN AREA = 'DG-SDT' AND WORK_SHOP = 'SMT' THEN 75
              WHEN AREA LIKE '%SSD' AND WORK_SHOP = 'SMT' THEN 73
              ELSE 95
         END)  AS STA_COM_EFF,
        MAX(COM_EFF) AS ACT_COM_EFF
FROM
(
    WITH  A AS
    (
           SELECT E.WORK_DATE
            FROM
            (SELECT TO_CHAR(FDATE,'yyyymmdd') AS WORK_DATE
            FROM
            (SELECT TRUNC(sysdate, 'MONTH') + LEVEL - 1 AS FDATE  FROM DUAL CONNECT BY LEVEL <= 31 ) T
            WHERE TO_CHAR(FDATE, 'MM') = TO_CHAR(sysdate, 'MM')
            ) E
    ),
        B AS
        (
            SELECT WORK_DATE,AREA,WORK_SHOP,DIR_EFF,COM_EFF FROM
            (
                SELECT WORK_DATE , AREA , WORK_SHOP, SUM(TOTAL_TIME) T_TIME ,SUM(PROD_TIME) P_TIME,
                SUM(EXC_TIME) E_TIME,TRUNC(SUM(PROD_TIME) /( SUM(TOTAL_TIME) -SUM(EXC_TIME))*100,2) DIR_EFF,
                TRUNC(SUM(PROD_TIME) /SUM(TOTAL_TIME)*100,2) COM_EFF FROM USER_EFF
                WHERE 1=1 AND PROD_TIME > 0 AND TOTAL_TIME > 0 AND AREA IN( 'DG-SDT','HY-MEM') GROUP BY WORK_DATE, AREA, WORK_SHOP
            )
            UNION ALL
            SELECT WORK_DATE,AREA,WORK_SHOP,DIR_EFF,COM_EFF FROM
            (
                SELECT WORK_DATE ,AREA ,WORK_SHOP, SUM(TOTAL_TIME) T_TIME ,SUM(PROD_TIME) P_TIME,
                SUM(EXC_TIME) E_TIME ,TRUNC(SUM(PROD_TIME) /( SUM(TOTAL_TIME) -SUM(EXC_TIME))*100,2) DIR_EFF,
                TRUNC(SUM(PROD_TIME) /SUM(TOTAL_TIME)*100,2) COM_EFF FROM SSD_USER_EFF
                WHERE 1=1 AND PROD_TIME > 0 AND TOTAL_TIME > 0 AND AREA IN ('CSSD','ESSD') GROUP BY WORK_DATE, AREA, WORK_SHOP
            )
    )
    SELECT A.WORK_DATE, B.AREA, B.WORK_SHOP, NVL(B.DIR_EFF,0) DIR_EFF,
    NVL(B.COM_EFF,0) COM_EFF
    FROM A ,B
    WHERE A.WORK_DATE = B.WORK_DATE(+)
    ORDER BY WORK_DATE,AREA,WORK_SHOP
)
WHERE 1=1
AND AREA IN ('DG-SDT','HY-MEM','CSSD','ESSD')
AND WORK_SHOP IN ('SMT','后段')
AND WORK_SHOP = NVL(TRIM('SMT'),WORK_SHOP)
AND AREA = 'CSSD'
AND WORK_DATE >= '20180601'
AND WORK_DATE <= '20180628'
GROUP BY WORK_DATE,AREA,WORK_SHOP
ORDER BY WORK_DATE,AREA,WORK_SHOP
