SELECT rownum rn9__, A.*  FROM ( SELECT FACTORY AS FACTORY , RES_ID AS RES_ID , LINE_ID AS LINE_ID , ORDER_ID AS ORDER_ID , PCB_ID AS PCB_ID , LANE_ID AS LANE_ID , PROGRAM_NAME AS PROGRAM_NAME , PIN_NAME AS PIN_NAME , GROUP_ID AS GROUP_ID , PCBA_ID AS PCBA_ID , RANK_NUM AS RANK_NUM , POS_X AS POS_X , POS_Y AS POS_Y , VOLUME_UPPER AS VOLUME_UPPER , VOLUME AS VOLUME , VOLUME_LOWER AS VOLUME_LOWER , HEIGHT_UPPER AS HEIGHT_UPPER , HEIGHT AS HEIGHT , HEIGHT_LOWER AS HEIGHT_LOWER , AREA_UPPER AS AREA_UPPER , AREA AS AREA , AREA_LOWER AS AREA_LOWER , OFFSET_X_UPPER AS OFFSET_X_UPPER , OFFSET_X AS OFFSET_X , OFFSET_X_LOWER AS OFFSET_X_LOWER , OFFSET_Y_UPPER AS OFFSET_Y_UPPER , OFFSET_Y AS OFFSET_Y , OFFSET_Y_LOWER AS OFFSET_Y_LOWER , ERROR_CODE AS ERROR_CODE , EQ_TIME AS EQ_TIME , EAP_TIME AS EAP_TIME , MES_IF AS MES_IF , MES_IF_TIME AS MES_IF_TIME , RET_TIME AS RET_TIME
FROM (SELECT
  A.FACTORY       ,
  A.RES_ID        ,
  A.LINE_ID       ,
  A.ORDER_ID      ,
  A.PCB_ID        ,
  A.LANE_ID       ,
  A.PROGRAM_NAME  ,
  A.PIN_NAME      ,
  A.GROUP_ID      ,
  A.PCBA_ID       ,
  A.RANK_NUM      ,
  A.POS_X         ,
  A.POS_Y         ,
  A.VOLUME_UPPER  ,
  A.VOLUME        ,
  A.VOLUME_LOWER  ,
  A.HEIGHT_UPPER  ,
  A.HEIGHT        ,
  A.HEIGHT_LOWER  ,
  A.AREA_UPPER    ,
  A.AREA          ,
  A.AREA_LOWER    ,
  A.OFFSET_X_UPPER,
  A.OFFSET_X      ,
  A.OFFSET_X_LOWER,
  A.OFFSET_Y_UPPER,
  A.OFFSET_Y      ,
  A.OFFSET_Y_LOWER,
  A.ERROR_CODE    ,
  A.EQ_TIME      ,
  A.EAP_TIME      ,
  A.MES_IF        ,
  A.MES_IF_TIME   ,
  A.RET_TIME
FROM CRASSPIDFT A
WHERE 1=1
  AND A.FACTORY = NVL(trim( 'RCM1' ),A.FACTORY)
  AND A.EQ_TIME >=  '20180627' || '08' || '30' ||'00'
  AND A.EQ_TIME <  '20180628' || '08' || '30' ||'00'
  AND A.LINE_ID = NVL (TRIM ( ' ' ), A.LINE_ID)
  AND A.RES_ID = NVL (TRIM ( 'PARMI-SPI-001' ), A.RES_ID)
  AND A.PCB_ID LIKE NVL(TRIM( '5J604518' ), A.PCB_ID)||'%'
  AND A.ORDER_ID LIKE NVL(TRIM( 'DBFB18060XC' ), A.ORDER_ID)||'%'
  AND A.LANE_ID LIKE NVL(TRIM( ' ' ), A.LANE_ID)||'%'
  AND A.PROGRAM_NAME LIKE NVL(TRIM( ' ' ), A.PROGRAM_NAME)||'%'
ORDER BY   A.FACTORY, A.LINE_ID, A.RES_ID, A.EQ_TIME) A
 ) A  WHERE ROWNUM < 10000
