SELECT rownum rn9__, A.*  FROM ( SELECT CUSTOMER_REPORT_1 AS CUSTOMER_REPORT_1 , CUSTOMER_REPORT_2 AS CUSTOMER_REPORT_2 , CUSTOMER_REPORT_3 AS CUSTOMER_REPORT_3 , REPORT_TIME AS REPORT_TIME , FA_REPORT_1 AS FA_REPORT_1 , FA_REPORT_2 AS FA_REPORT_2 , FA_REPORT_3 AS FA_REPORT_3 , TRAN_USER_ID AS TRAN_USER_ID , TRAN_TIME AS TRAN_TIME , TRAN_COMMENT AS TRAN_COMMENT
FROM (SELECT CUSTOMER_REPORT_1,
  CUSTOMER_REPORT_2,
  CUSTOMER_REPORT_3,
  REPORT_TIME,
  FA_REPORT_1,
  FA_REPORT_2,
  FA_REPORT_3,
  TRAN_USER_ID,
  TRAN_TIME,
  TRAN_COMMENT
FROM CWIPREPRPT
WHERE 1=1
AND (case
         when trim( ' ' ) is null then
1
         when trim( ' ' ) = LOT_ID then
1
         else
0
       end) = 1
ORDER BY LOT_ID) A
 ) A  WHERE ROWNUM < 10000
