SELECT rownum rn9__, A.*  FROM ( SELECT FACTORY AS FACTORY , RES_ID AS RES_ID , LINE_ID AS LINE_ID , ORDER_ID AS ORDER_ID , PCB_ID AS PCB_ID , LANE_ID AS LANE_ID , PROGRAM_NAME AS PROGRAM_NAME , CYCLE_TIME AS CYCLE_TIME , RESULT AS RESULT , RES_DEFECT_QTY AS RES_DEFECT_QTY , MAN_DEFECT_QTY AS MAN_DEFECT_QTY , RES_PCBA_DEFECT_QTY AS RES_PCBA_DEFECT_QTY , MAN_PCBA_DEFECT_QTY AS MAN_PCBA_DEFECT_QTY , IMAGE_PATH AS IMAGE_PATH , REF_NAME AS REF_NAME , PCBA_ID AS PCBA_ID , RANK_NUM AS RANK_NUM , MAT_ID AS MAT_ID , RES_DEFECT AS RES_DEFECT , MAN_DEFECT AS MAN_DEFECT , EQ_TIME AS EQ_TIME , EAP_TIME AS EAP_TIME , MES_IF AS MES_IF , MES_IF_TIME AS MES_IF_TIME , RET_TIME AS RET_TIME
FROM (SELECT
   A.FACTORY,
   A.RES_ID,
   A.LINE_ID,
   A.ORDER_ID,
   A.PCB_ID,
   A.LANE_ID,
   A.PROGRAM_NAME,
   A.CYCLE_TIME,
   A.RESULT,
   A.RES_DEFECT_QTY,
   A.MAN_DEFECT_QTY,
   A.RES_PCBA_DEFECT_QTY,
   A.MAN_PCBA_DEFECT_QTY,
   A.IMAGE_PATH,
   B.REF_NAME,
   B.PCBA_ID,
   B.RANK_NUM,
   B.MAT_ID,
   B.RES_DEFECT,
   B.MAN_DEFECT,
   A.EQ_TIME,
   A.EAP_TIME,
   A.MES_IF,
   A.MES_IF_TIME,
   A.RET_TIME
FROM CRASAOIPRD A, CRASAOIDFT B
WHERE 1=1
  AND A.FACTORY = NVL(trim( 'RCM1' ),A.FACTORY)
  AND A.FACTORY = B.FACTORY(+)
  AND A.LINE_ID = B.LINE_ID(+)
  AND A.RES_ID = B.RES_ID(+)
  AND A.PCB_ID = B.PCB_ID(+)
  AND A.EQ_TIME >=  '20180627' || '19' || '30' ||'00'
  AND A.EQ_TIME <  '20180628' || '08' || '30' ||'00'
  AND A.LINE_ID = NVL (TRIM ( ' ' ), A.LINE_ID)
  AND A.RES_ID = NVL (TRIM ( 'PARMI-AOI-002' ), A.RES_ID)
  AND A.PCB_ID LIKE NVL(TRIM( ' ' ), A.PCB_ID)||'%'
  AND A.ORDER_ID LIKE NVL(TRIM( 'DBFB18060XC' ), A.ORDER_ID)||'%'
  AND A.LANE_ID LIKE NVL(TRIM( ' ' ), A.LANE_ID)||'%'
  AND A.PROGRAM_NAME LIKE NVL(TRIM( ' ' ), A.PROGRAM_NAME)||'%'
ORDER BY   A.FACTORY, A.LINE_ID, A.RES_ID, A.EQ_TIME) A
 ) A  WHERE ROWNUM < 10000
