SELECT rownum rn9__, A.*  FROM ( SELECT LOT_ID AS LOT_ID , DEFECT_CODE AS DEFECT_CODE , DEFECT_QTY AS DEFECT_QTY , TRAN_TIME AS TRAN_TIME , SYS_TRAN_TIME AS SYS_TRAN_TIME , TRAN_USER_ID AS TRAN_USER_ID , CLEAN_FLAG AS CLEAN_FLAG , CLEAN_HIST_SEQ AS CLEAN_HIST_SEQ , CLEAN_USER_ID AS CLEAN_USER_ID , CLEAN_TIME AS CLEAN_TIME , MAT_ID AS MAT_ID , MAT_VER AS MAT_VER , FLOW AS FLOW , OPER AS OPER , CAUSE_OPER AS CAUSE_OPER , ATTACH_FILE_1 AS ATTACH_FILE_1 , ATTACH_FILE_2 AS ATTACH_FILE_2 , ATTACH_FILE_3 AS ATTACH_FILE_3 , DEFECT_COMMENT AS DEFECT_COMMENT , HIST_SEQ AS HIST_SEQ , SEQ_NUM AS SEQ_NUM , STATUS AS STATUS , LINE_ID AS LINE_ID , SHIFT AS SHIFT , DEFECT_TYPE AS DEFECT_TYPE , DEFECT_LOCATION AS DEFECT_LOCATION , DUTY_USER AS DUTY_USER , BOARD_SIDE AS BOARD_SIDE , MAT_VENDER AS MAT_VENDER , MAT_CYCLE AS MAT_CYCLE , CMF_1 AS CMF_1 , CREATE_USER_ID AS CREATE_USER_ID , CREATE_TIME AS CREATE_TIME
FROM (SELECT M.LOT_ID,
M.DEFECT_CODE,
M.DEFECT_QTY,
TO_CHAR(to_date(trim(M.TRAN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') TRAN_TIME,
TO_CHAR(to_date(trim(M.SYS_TRAN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') SYS_TRAN_TIME,
M.TRAN_USER_ID,
M.CLEAN_FLAG,
M.CLEAN_HIST_SEQ,
M.CLEAN_USER_ID,
TO_CHAR(to_date(trim(M.CLEAN_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') CLEAN_TIME,
M.MAT_ID,
M.MAT_VER,
M.FLOW,M.OPER,
M.CAUSE_OPER,
M.ATTACH_FILE_1,
M.ATTACH_FILE_2,
M.ATTACH_FILE_3,
M.DEFECT_COMMENT,
C.HIST_SEQ,
C.SEQ_NUM,
C.STATUS,
C.LINE_ID,
(CASE
  WHEN C.SHIFT_ID = ' ' THEN ' '
  ELSE (SELECT G.DATA_1 FROM MGCMTBLDAT G WHERE G.TABLE_NAME = 'SHIFT' AND G.KEY_1 = C.SHIFT_ID)
END) AS SHIFT,
C.DEFECT_TYPE,
C.DEFECT_LOCATION,
C.DUTY_USER,
C.BOARD_SIDE,
C.MAT_VENDER,
C.MAT_CYCLE,
C.CMF_1,
C.CREATE_USER_ID,
TO_CHAR(to_date(trim(C.CREATE_TIME),'yyyy-mm-dd,hh24:mi:ss'), 'YYYY-MM-DD HH24:MI:SS') CREATE_TIME
FROM MWIPLOTDFT M LEFT JOIN CWIPDFTEXT C ON M.FACTORY = C.FACTORY
AND M.LOT_ID = C.LOT_ID
WHERE M.FACTORY = trim( 'RCM1' ) AND
    (case
         when trim( '023000000003000311' ) is null then
1
         when trim( '023000000003000311' ) = M.LOT_ID then
1
         else
0
       end) = 1
ORDER BY M.LOT_ID) A
 ) A  WHERE ROWNUM < 10000
