SELECT FACTORY ,LINE_ID ,RES_ID ,COUNT(RESULT) AS Total_Cnt, SUM(RESULT) AS NG_CNT, (COUNT(RESULT) - SUM(RESULT)) AS GOOD_CNT,
 ROUND(((COUNT(RESULT) - SUM(RESULT))/decode(COUNT(RESULT),0,1,COUNT(RESULT))) * 100,2) AS GOOD_RATE , ROUND((SUM(RESULT)/decode(COUNT(RESULT),0,1,COUNT(RESULT)))*100,2) AS NG_RATE
FROM CRASAOIPRD S
WHERE S.FACTORY = NVL(trim('RCM1'),S.FACTORY)
AND S.RES_ID = NVL(trim(' '),S.RES_ID)
AND S.EQ_TIME >= '20180627'
AND S.EQ_TIME <= '20180628'||'235959'
GROUP BY FACTORY,LINE_ID, RES_ID
