select WORK_DATE,
       PROD_QTY,
       DEFT_QTY,
       PLAN_QTY,
       ROUND( PROD_QTY/decode(PLAN_QTY,0,1,PLAN_QTY),4 )*100 AS PROD_RATE,
       ROUND( DEFT_QTY/decode(PLAN_QTY,0,1,PLAN_QTY),4 )*100 AS DEFT_RATE
from(
  select TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM') WORK_DATE,
       SUM(H.QTY_1) PROD_QTY,
       SUM(CASE WHEN H.TRAN_CODE = 'COLLECT_DFT' THEN QTY_1 ELSE 0 END) DEFT_QTY,
       (SELECT SUM(M.ORD_QTY) FROM MWIPORDSTS M where  SUBSTR(M.PLAN_START_TIME,0,6) = TO_CHAR(sysdate,'yyyymm') and M.ORD_CMF_4 in('200010','200020','200030','200040','200050') )  AS PLAN_QTY
  from MWIPLOTHIS H
  where H.FACTORY = 'RCM1'
    AND H.HIST_DEL_FLAG = ' '
    AND H.LOT_CMF_17 in('200010','200020','200030','200040','200050')
    AND (CASE WHEN LOT_CMF_15 IN ( 'S',' ') AND TRAN_CODE IN ('END', 'COLLECT_DFT')
                THEN 1
                WHEN LOT_CMF_15 IN ( 'T','B') AND TRAN_CODE IN ('CREATE','END', 'COLLECT_DFT')
                THEN 1
          END )  = 1
    AND OLD_OPER = '120070'
    AND H.TRAN_TIME >= TO_CHAR(sysdate,'yyyymm')
  group by TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM')
)
