WITH PROD_TEMP AS (
  select
         (CASE WHEN H.TRAN_TIME >= SUBSTR(H.TRAN_TIME,0,8)||'0800' THEN TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM-DD')
            ELSE TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS') -1,'YYYY-MM-DD')
          END
          )
          WORK_DATE,
          H.LINE_ID,
         COUNT(DISTINCT H.LOT_ID) PROD_QTY
    from CWIPLOTMVH H
      LEFT JOIN MWIPMATDEF D
          ON H.FACTORY = D.FACTORY    AND H.MAT_ID = D.MAT_ID
    where H.FACTORY = 'RCM1'
      AND H.SEQ_NUM = 1
      AND H.HIST_DEL_FLAG = ' '
      AND H.LINE_ID like '100%'
      AND H.OLD_OPER = '120070'
      AND (CASE WHEN H.BOARD_SIDE IN ( 'S',' ') AND H.TRAN_CODE IN ('END', 'COLLECT_DFT')
                  THEN 1
                WHEN H.BOARD_SIDE IN ( 'T','B') AND H.TRAN_CODE IN ('CREATE','END', 'COLLECT_DFT')
                  THEN 1
            END )  = 1
      AND H.TRAN_TIME >= GETSHIFTDAY('FROM','080000')
      AND H.TRAN_TIME < GETSHIFTDAY('TO','080000')
    group by (CASE WHEN H.TRAN_TIME >= SUBSTR(H.TRAN_TIME,0,8)||'0800' THEN TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS'),'YYYY-MM-DD')
            ELSE TO_CHAR(to_date(H.TRAN_TIME,'YYYY-MM-DD HH24MISS') -1,'YYYY-MM-DD')
          END
          ),H.LINE_ID
  ),
  PLAN_TEMP AS (
    select
            TO_CHAR(TO_DATE(P.WORK_DATE,'YYYYMMDD'),'YYYY-MM-DD') WORK_DATE,
            P.LINE_ID,
            SUM(P.PLAN_ORD_QTY) PLAN_QTY
    from CWIPORDPLN P
      LEFT JOIN MWIPMATDEF D
          ON P.FACTORY = D.FACTORY    AND P.MAT_ID = D.MAT_ID
      where P.LINE_ID LIKE '100%'
      AND P.DELETE_FLAG = ' '
      and P.ORD_CMF_1 = 'SMT'
      and P.WORK_DATE = (CASE WHEN SUBSTR(SYSDATE,9,6)>='080000' THEN TO_CHAR(SYSDATE,'YYYYMMDD') ELSE TO_CHAR(SYSDATE-1,'YYYYMMDD') END)
  GROUP BY TO_CHAR(TO_DATE(P.WORK_DATE,'YYYYMMDD'),'YYYY-MM-DD'),P.LINE_ID
  ),
  BASIC AS (SELECT A.WORK_DATE,B.KEY_1 LINE_ID,0 PLAN_QTY,0 PROD_QTY,0 RATE FROM
  (SELECT (CASE WHEN SUBSTR(SYSDATE,9,6)>='080000' THEN TO_CHAR(SYSDATE,'YYYY-MM-DD') ELSE TO_CHAR(SYSDATE-1,'YYYY-MM-DD') END) WORK_DATE FROM DUAL) A,
  (SELECT DISTINCT KEY_1 from MGCMTBLDAT WHERE TABLE_NAME='SUB_AREA' AND FACTORY = 'RCM1' AND KEY_1 LIKE '100%') B
  )
select W.WORK_DATE,W.LINE_ID,NVL(P.PLAN_QTY,0) PLAN_QTY,NVL(D.PROD_QTY,0) PROD_QTY,ROUND(NVL(D.PROD_QTY,0)/decode(NVL(P.PLAN_QTY,0),0,null,P.PLAN_QTY),4)*100 AS RATE from BASIC W
  left join PROD_TEMP D ON W.WORK_DATE = D.WORK_DATE AND W.LINE_ID = D.LINE_ID
  left join PLAN_TEMP P ON W.WORK_DATE = P.WORK_DATE AND W.LINE_ID = P.LINE_ID
ORDER BY 1,2
