SELECT FACTORY ,LINE_ID ,RES_ID ,COUNT(RESULT) AS Total_Cnt, SUM(RESULT) AS NG_CNT, (COUNT(RESULT) - SUM(RESULT)) AS GOOD_CNT,     
 ROUND(((COUNT(RESULT) - SUM(RESULT))/COUNT(RESULT)) * 100,2) AS GOOD_RATE , ROUND((SUM(RESULT)/COUNT(RESULT))*100,2) AS NG_RATE  
FROM CRASSPIPRD 
WHERE FACTORY='RCM1' 
AND LINE_ID = '100050' 
AND substr(EQ_TIME,0,8) = to_char(sysdate, 'YYYYMMDD')  
GROUP BY FACTORY,LINE_ID, RES_ID