SELECT RES_ID, NEW_STATUS, to_char(to_date(EQ_TIME,'yyyymmdd hh24miss'),'yyyy-mm-dd hh24:mi:ss') EQ_TIME, MES_IF_TIME, RET_TIME
FROM(
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='KY-SPI-001'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
    UNION
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='X4I-FCM-001'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
    UNION
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='X2-FCM-001'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
    UNION
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='SAKI-AOI-001'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
    UNION
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='HELLER-OVEN-001'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
    UNION
    SELECT A.RES_ID, A.NEW_STATUS, A.EQ_TIME, A.MES_IF_TIME,A.RET_TIME FROM CRASRESSTS A,
    (SELECT RES_ID, MAX(EQ_TIME) EQ_TIME FROM CRASRESSTS WHERE FACTORY='RCM1' AND RES_ID='SAKI-AOI-002'
      GROUP BY RES_ID) B WHERE A.FACTORY='RCM1' AND A.RES_ID=B.RES_ID AND A.EQ_TIME=B.EQ_TIME AND ROWNUM=1
)
