WITH A AS
  (SELECT TO_CHAR(sysdate,'yyyymm') AS WORK_DATE ,
    M.KEY_1 LINE_ID ,
    M.DATA_1 LINE_DESC
  FROM MGCMTBLDAT M
  WHERE M.TABLE_NAME = 'SUB_AREA'
  AND M.FACTORY      = 'RCM1'
  ),
  B AS
  (SELECT SUBSTR(P.WORK_DATE,0,6) WORK_DATE ,
    P.LINE_ID,
    SUM(P.PLAN_ORD_QTY) PLAN_ORD_QTY,
    ROUND(SUM(P.PLAN_ORD_QTY)/to_number(TO_CHAR(sysdate, 'dd')),0) AS AVG_QTY
  FROM cwipordpln P
  WHERE
      P.ORD_CMF_1  = 'SMT'
  AND P.WORK_DATE  = TO_CHAR(sysdate,'yyyymmdd')
  AND P.FACTORY    = 'RCM1'
  AND P.DELETE_FLAG = ' '
  GROUP BY SUBSTR(P.WORK_DATE,0,6) ,
    P.LINE_ID
  ),
  C AS
  (SELECT SUBSTR(P.WORK_DATE,0,6) WORK_DATE ,  
    P.SUB_AREA AS LINE_ID,
    SUM(P.TRAN_COUNT) ACT_TRAN_QTY
  FROM cwipprdsum P
  WHERE P.OPER     = '120070'
  AND P.WORK_DATE  = TO_CHAR(sysdate,'yyyymmdd')
  AND P.FACTORY    = 'RCM1'
  GROUP BY SUBSTR(P.WORK_DATE,0,6) ,
    P.SUB_AREA
  )
SELECT A.WORK_DATE,
  A.LINE_ID ,
  A.LINE_DESC,
  B.PLAN_ORD_QTY PLAN_QTY,
  C.ACT_TRAN_QTY PROD_QTY,
  TRUNC (C.ACT_TRAN_QTY    /B.PLAN_ORD_QTY ,3)*100               AS RATE ,
  B.AVG_QTY
FROM A,
  B,
  C
WHERE A.LINE_ID = B.LINE_ID(+)
AND A.LINE_ID   = C.LINE_ID(+)
ORDER BY A.LINE_ID
